server:
  port: 8083

spring:
  application:
    name: investment-service
  datasource:
    url: jdbc:mysql://localhost:3306/investment_db
    username: root
    password: Root@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


