server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/auth/**,/customers/**

        - id: telecom-service
          uri: lb://telecom-usage-service
          predicates:
            - Path=/usage/**

        - id: investment-service
          uri: lb://investment-service
          predicates:
            - Path=/plans/**,/investments/**,/invest/**,/redeem/**

        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/portfolio/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
